---
sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js: 11
branches:
  only:
    - master
notifications:
  email: false
script:
  - yarn validate
after_success:
  - yarn report-coverage
